services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ewm_user
      POSTGRES_PASSWORD: ewm_pass
      POSTGRES_DB: ewm_main_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10
    ports:
      - "5434:5432"