server:
  port: 9090

spring:
  application:
    name: stats-server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm_main_db?currentSchema=stats}
    username: ${SPRING_DATASOURCE_USERNAME:ewm_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm_pass}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: stats

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgres.sql

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true