CREATE SCHEMA IF NOT EXISTS requests;

create TABLE IF NOT EXISTS requests.requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(100)
);