CREATE SCHEMA IF NOT EXISTS requests;

create TABLE IF NOT EXISTS requests.requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT REFERENCES ewm.events(id),
    requester_id BIGINT REFERENCES ewm.users(id),
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(100)
);