server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**,/users/*/events/*/requests/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/users/*/comments/**,/events/*/comments/**,/comments/**,/admin/comments/**
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/admin/**,/users/**,/events,/events/**,/categories,/categories/**,/compilations,/compilations/**
