grpc:
  server:
    port: 0

spring:
  application:
    name: analyzer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/ewm_main_db}
    username: ${SPRING_DATASOURCE_USERNAME:ewm_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm_pass}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: stats
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgres.sql
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  server:
    port: 0
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  kafka:
    topics:
      user-actions: stats.user-actions.v1
      events-similarity: stats.events-similarity.v1
    consumer:
      user-actions-group-id: analyzer-user-actions
      events-similarity-group-id: analyzer-events-similarity
  recommendations:
    recent-interactions-limit: 20
    similar-candidates-limit: 100
    nearest-neighbors-k: 10
