server:
  port: 8080

spring:
  application:
    name: main-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm_main_db?currentSchema=ewm}
    username: ${SPRING_DATASOURCE_USERNAME:ewm_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm_pass}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ewm
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgres.sql

stats-server:
  url: ${STATS_SERVER_URL:http://localhost:9090}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: mappings,health
  endpoint:
    health:
      show-details: always

logging.level:
  ewm: DEBUG
  stats.client: DEBUG
  org.springframework.beans: DEBUG
  org.springframework.context: DEBUG
  org.springframework.boot.autoconfigure: DEBUG