CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    email VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(120)      NOT NULL,
    annotation         VARCHAR(2000)     NOT NULL,
    description        TEXT              NOT NULL,
    category_id        BIGINT            NOT NULL REFERENCES categories(id),
    initiator_id       BIGINT            NOT NULL REFERENCES users(id),
    event_date         TIMESTAMP         NOT NULL,
    created_on         TIMESTAMP         NOT NULL DEFAULT NOW(),
    published_on       TIMESTAMP,
    paid               BOOLEAN           NOT NULL DEFAULT FALSE,
    participant_limit  INTEGER           NOT NULL DEFAULT 0,
    request_moderation BOOLEAN           NOT NULL DEFAULT TRUE,
    state              VARCHAR(50)       NOT NULL,
    lat                 DOUBLE PRECISION,
    lon                 DOUBLE PRECISION
);

create TABLE IF NOT EXISTS requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT REFERENCES events(id),
    requester_id BIGINT REFERENCES users(id),
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(100)
);

create TABLE IF NOT EXISTS compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50)                             NOT NULL,
    pinned BOOLEAN                                 NOT NULL
);

create TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL REFERENCES compilations (id),
    event_id       BIGINT NOT NULL REFERENCES events (id),
    CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(2000) NOT NULL,
    event_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_comment_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_user FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);